version: '3.8'

services:
  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome-debug:latest
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - 7901:5900

  firefox:
    image: selenium/node-firefox-debug:latest
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - 7900:5900

  client:
    build:
      context: .
      dockerfile: ./compose/client/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_client
    container_name: client
    volumes:
      - .:/app:z
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.client/.client
    depends_on:
      - chrome
      - firefox

networks:
  default:
    external:
      name: {{ cookiecutter.project_slug }}_staging
