[tool.black]
line-length = 120

[tool.isort]
profile = "black"
known_first_party = ["{{cookiecutter.project_slug}}", "config"]
skip = ["venv/"{% if cookiecutter.use_drf == 'y' %}, "swagger_client/"{% endif %}]
skip_glob = "**/migrations/*.py"
