#!/bin/bash

# Commands for flushing the database between functional tests from client container
# Use: docker exec -e <ENV_VARS> -i <CONTAINER> /bin/bash < /create_user

set -o errexit
set -o pipefail
set -o nounset

source /app/compose/client/django/_sourced/env

python manage.py create_user ${CLIENT_EMAIL} ${CLIENT_PASSWORD} "${CLIENT_NAME}" ${FLAGS}
